dist: xenial
sudo: false

language: generic

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server
  - docker

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential
  hosts:
    - grpcs_1.test
    - grpcs_2.test

env:
  global:
    - KONG_TEST_PG_DATABASE=travis
    - KONG_TEST_PG_USER=postgres
    - JOBS=2
    - DOCKER_MACHINE_ARM64_NAME=travis-ci-kong-${TRAVIS_JOB_ID}
    - KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools
  matrix:
    - KONG_TEST_DATABASE=postgres TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=integration
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=integration
    - KONG_TEST_DATABASE=off TEST_SUITE=dbless
    - KONG_TEST_DATABASE=postgres TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=2.2 TEST_SUITE=plugins
    - KONG_TEST_DATABASE=cassandra CASSANDRA=3.9 TEST_SUITE=plugins
    - TEST_SUITE=pdk

stages:
  - build release
  - lint and unit
  - test
  - Deploy daily build
  - Release

install:
  - export PATH=$PATH:/usr/local/openresty/bin/:/usr/local/kong/bin/:/usr/local/openresty/nginx/sbin/
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make build-release
  - sudo dpkg -i $KONG_BUILD_TOOLS_LOCATION/output/kong*.deb
  - sudo rm -rf kong-build-tools
  - sudo make dev
  - sudo chown -R travis:travis $HOME
  - mkdir -p /home/travis/build/Kong/kong/servroot/logs/
  - source .ci/setup_env.sh

jobs:
  include:
    - stage: build release
      install: skip
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make build-release
    - stage: lint and unit
      script:
      - luacheck -q .
      - scripts/autodoc-admin-api
      - bin/busted -v -o gtest spec/01-unit
      env:
        - KONG_DATABASE=none
    - stage: release
      install: skip
      script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=src RESTY_IMAGE_BASE=src KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=ubuntu RESTY_IMAGE_TAG=trusty KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=ubuntu RESTY_IMAGE_TAG=xenial KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=ubuntu RESTY_IMAGE_TAG=bionic KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=debian RESTY_IMAGE_TAG=stretch KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=debian RESTY_IMAGE_TAG=jessie KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=centos RESTY_IMAGE_TAG=6 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=centos RESTY_IMAGE_TAG=7 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=apk RESTY_IMAGE_BASE=alpine RESTY_IMAGE_TAG=1 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=rhel RESTY_IMAGE_TAG=6 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=rhel RESTY_IMAGE_TAG=7 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - script:
      - make setup-ci
      - make release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=amazonlinux RESTY_IMAGE_TAG=1 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=${TRAVIS_TAG}
      if: tag IS present AND tag ~= 1.
    - stage: deploy daily build
      install: skip
      script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=ubuntu RESTY_IMAGE_TAG=trusty KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=ubuntu RESTY_IMAGE_TAG=xenial KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=ubuntu RESTY_IMAGE_TAG=bionic KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=debian RESTY_IMAGE_TAG=stretch KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=deb RESTY_IMAGE_BASE=debian RESTY_IMAGE_TAG=jessie KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=centos RESTY_IMAGE_TAG=6 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=centos RESTY_IMAGE_TAG=7 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=apk RESTY_IMAGE_BASE=alpine RESTY_IMAGE_TAG=latest KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=rhel RESTY_IMAGE_TAG=6 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=rhel RESTY_IMAGE_TAG=7 KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
    - script:
      - make setup-ci
      - make nightly-release
      install: skip
      env: PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=amazonlinux RESTY_IMAGE_TAG=latest KONG_PACKAGE_NAME=${PWD##*/} KONG_VERSION=`date +%Y-%m-%d` REPOSITORY_NAME=${PWD##*/}-nightly REPOSITORY_OS_NAME=$TRAVIS_BRANCH
      if: type=cron
script:
  - .ci/run_tests.sh
